# Generated by Django 2.2.16 on 2021-09-27 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('basket', '0013_auto_20200305_1448'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0026_auto_20200305_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='CowpayPaymentRecord',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('payment_gateway_reference_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('merchant_reference_id', models.CharField(max_length=512)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.Basket')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
