# Generated by Django 2.2.24 on 2025-01-14 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0032_alter_source_card_type'),
        ('payment', '0032_sdnfallbackdata'),
    ]

    operations = [
    ]
