# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-14 11:41
from __future__ import unicode_literals

from django.db import migrations

import ecommerce.extensions.offer.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0023_offerassignmentemailattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionBenefit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=(ecommerce.extensions.offer.mixins.BenefitWithoutRangeMixin, ecommerce.extensions.offer.mixins.PercentageBenefitMixin, 'offer.percentagediscountbenefit'),
        ),
        migrations.CreateModel(
            name='SubscriptionCondition',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=(ecommerce.extensions.offer.mixins.ConditionWithoutRangeMixin, ecommerce.extensions.offer.mixins.SingleItemConsumptionConditionMixin, 'offer.condition'),
        ),
    ]
