# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-14 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0036_coupon_notify_email_attribute'),
        ('offer', '0023_offerassignmentemailattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_condition', to='catalogue.Product', verbose_name='Subscription'),
        ),
    ]
